import { readFile, writeFile } from 'node:fs/promises';

// Deterministic assembly of the existing modules. No fixture or answer IDs.
const root = new URL('../', import.meta.url);
const read = path => readFile(new URL(path, root), 'utf8');
const withoutImports = text => text.replace(/^import .*;\n/gmu, '');
const reader = await read('xdr/brute-force/read-alerts.mjs');
const safeReader = reader.slice(reader.indexOf('// Conservative'), reader.indexOf('export async function readAlerts'));
const matcher = await read('xdr/brute-force/match-patterns.mjs');
const matcherBody = matcher.slice(matcher.indexOf('// This accepts'));
const catalog = JSON.parse(await read('xdr/brute-force/patterns.json'));
const compiled = [
  '// Generated by scripts/xdr-pack.mjs from the readable source modules.\n'
    + '// No imports or runtime filesystem reads are required.\n',
  await read('xdr/brute-force/address.mjs'),
  safeReader,
  withoutImports(await read('xdr/brute-force/observe.mjs')),
  `export const patternCatalog = ${JSON.stringify(catalog, null, 2)};\n`,
  matcherBody,
  await read('xdr/jev-client.mjs'),
  withoutImports(await read('xdr/brute-force/decision-core.mjs')),
].join('\n');
if (process.argv.includes('--check')) {
  if (await read('xdr/brute-force/decide.mjs') !== compiled) throw new Error('XDR_ENTRY_OUT_OF_DATE');
} else {
  await writeFile(new URL('xdr/brute-force/decide.mjs', root), compiled);
}
console.log('XDR 독립 실행 파일과 원본 모듈의 일치를 확인했습니다.');
